# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-10 20:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('date_started', models.DateField()),
                ('students', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_published', models.DateTimeField()),
                ('circuit_diagram_type', models.PositiveSmallIntegerField(choices=[(1, 'Open circuit'), (2, 'Short circuit'), (3, 'Resistance'), (4, 'Capacitance'), (5, 'Parallel res/cap'), (6, 'Series res/cap'), (7, 'Inductance'), (8, 'Parallel res/ind'), (9, 'Series res/ind')])),
                ('R_gen', models.PositiveSmallIntegerField()),
                ('U_gen', models.PositiveSmallIntegerField(default=1000)),
                ('T_gen', models.PositiveSmallIntegerField(verbose_name='pulse time')),
                ('L_line', models.PositiveSmallIntegerField(verbose_name='length')),
                ('X_line', models.PositiveSmallIntegerField(verbose_name='position')),
                ('T_line', models.PositiveSmallIntegerField()),
                ('Ro_line', models.PositiveSmallIntegerField()),
                ('R_load', models.PositiveSmallIntegerField()),
                ('L_load', models.PositiveSmallIntegerField()),
                ('C_load', models.PositiveSmallIntegerField()),
                ('T_delay_osc', models.PositiveSmallIntegerField(verbose_name='delay')),
                ('T_sweep_osc', models.PositiveSmallIntegerField(verbose_name='sweep')),
                ('comment', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('number', models.PositiveSmallIntegerField()),
                ('description', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_status', models.PositiveSmallIntegerField(choices=[(1, 'New'), (2, 'Sent to check'), (3, 'Passed'), (4, 'Declined')], verbose_name='status')),
                ('created_date', models.DateTimeField()),
                ('changed_date', models.DateTimeField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='longlines.Task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskTaskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.PositiveSmallIntegerField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='longlines.Task')),
                ('task_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='longlines.TaskList')),
            ],
        ),
        migrations.AddField(
            model_name='tasklist',
            name='tasks',
            field=models.ManyToManyField(through='longlines.TaskTaskList', to='longlines.Task'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='longlines.TaskProgress'),
        ),
        migrations.AddField(
            model_name='learninggroup',
            name='task_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='longlines.TaskList'),
        ),
        migrations.AddField(
            model_name='learninggroup',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tutors', related_query_name='tutor', to=settings.AUTH_USER_MODEL),
        ),
    ]
