# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-07 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('longlines', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskprogress',
            options={'verbose_name': 'Task progress', 'verbose_name_plural': 'Task progresses'},
        ),
        migrations.AlterField(
            model_name='taskprogress',
            name='changed_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='taskprogress',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='taskprogress',
            name='task_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Новая'), (2, 'Ожидает проверки'), (3, 'Выполнено'), (4, 'Отклонено')], default=1, verbose_name='status'),
        ),
    ]
