# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-10 21:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('longlines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learninggroup',
            name='students',
            field=models.ManyToManyField(related_name='students', to=settings.AUTH_USER_MODEL),
        ),
    ]
